all:
	dot -Tsvg AliceBobMultisig.dot -o AliceBobMultisig.svg
	dot -Tsvg BobCharlieMultisig.dot -o BobCharlieMultisig.svg
	dot -Tsvg beforeTurn.dot -o beforeTurn.svg
	dot -Tsvg simple1.dot -o simple1.svg
	dot -Tsvg simple2.dot -o simple2.svg
	dot -Tsvg afterTurn.dot -o afterTurn.svg
	dot -Tsvg transitiveGame1.dot -o transitiveGame1.svg
	dot -Tsvg transitiveGame2.dot -o transitiveGame2.svg
	dot -Tsvg transitiveGame3.dot -o transitiveGame3.svg
	dot -Tsvg transitiveGame4.dot -o transitiveGame4.svg

clean:
	rm -rf *.svg
