all:
	dot -Tsvg beforeTurn.dot -o beforeTurn.svg
	dot -Tsvg simple1.dot -o simple1.svg
	dot -Tsvg simple2.dot -o simple2.svg
	dot -Tsvg afterTurn.dot -o afterTurn.svg
	dot -Tsvg transitiveGame1.dot -o transitiveGame1.svg

clean:
	rm -rf beforeTurn.svg simple1.svg  simple2.svg  afterTurn.svg  transitiveGame1.svg 

reallyclean:
	rm -rf *.svg
