all:
	dot -Tsvg AliceBobMultisig.dot -o AliceBobMultisig.svg
	dot -Tsvg BobCharlieMultisig.dot -o BobCharlieMultisig.svg
	dot -Tsvg beforeTurn.dot -o beforeTurn.svg
	dot -Tsvg simple1.dot -o simple1.svg
	dot -Tsvg simple2.dot -o simple2.svg
	dot -Tsvg afterTurn.dot -o afterTurn.svg

clean:
	rm -rf *.svg
