all:
	dot -Tsvg collusion.dot -o collusion.svg
	dot -Tsvg graph.dot -o graph.svg
	dot -Tsvg turn_add_pos_arrow.dot -o turn_add_pos_arrow.svg
	dot -Tsvg turn_add_pos_btc.dot -o turn_add_pos_btc.svg
	dot -Tsvg turn_add_neg_btc.dot -o turn_add_neg_btc.svg
	dot -Tsvg turn_steal_btc.dot -o turn_steal_btc.svg
	dot -Tsvg turn_end.dot -o turn_end.svg
	dot -Tsvg AliceBobMultisig.dot -o AliceBobMultisig.svg
	dot -Tsvg AliceBobTIR.dot -o AliceBobTIR.svg
	dot -Tsvg transaction1.dot -o transaction1.svg
	dot -Tsvg transaction2.dot -o transaction2.svg

allmost:
	dot -Tsvg collusion.dot -o collusion.svg
	dot -Tsvg graph.dot -o graph.svg
	dot -Tsvg turn_add_pos_arrow.dot -o turn_add_pos_arrow.svg
	dot -Tsvg turn_add_pos_btc.dot -o turn_add_pos_btc.svg
	dot -Tsvg turn_add_neg_btc.dot -o turn_add_neg_btc.svg
	dot -Tsvg turn_steal_btc.dot -o turn_steal_btc.svg
	dot -Tsvg turn_end.dot -o turn_end.svg
	dot -Tsvg AliceBobTIR.dot -o AliceBobTIR.svg
	dot -Tsvg transaction1.dot -o transaction1.svg
	dot -Tsvg transaction2.dot -o transaction2.svg

clean:
	rm -rf collusion.svg turn_add_pos_arrow.svg turn_add_pos_btc.svg Turn_add_neg_btc.svg turn_steal_btc.svg turn_end.svg AliceBobMultisig.svg AliceBobTIR.svg transaction1.svg transaction2.svg
