all: networkhealth1.svg networkhealth2.svg networkhealth3.svg networkhealth4.svg

networkhealth1.svg: networkhealth1.dot
	dot -Tsvg networkhealth1.dot -o networkhealth1.svg

networkhealth2.svg: networkhealth2.dot
	dot -Tsvg networkhealth2.dot -o networkhealth2.svg

networkhealth3.svg: networkhealth3.dot
	dot -Tsvg networkhealth3.dot -o networkhealth3.svg

networkhealth4.svg: networkhealth4.dot
	dot -Tsvg networkhealth4.dot -o networkhealth4.svg
